# Generated by Django 3.1.7 on 2021-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210318_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('DSP', 'DSP'), ('IO', 'IO')], max_length=10, null=True),
        ),
    ]
