# Generated by Django 3.1.7 on 2021-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210319_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='officer_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
