# Generated by Django 3.1.7 on 2021-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210320_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='officer_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
