# Generated by Django 3.1.7 on 2021-03-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210320_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='officer_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
