# Generated by Django 3.1.7 on 2021-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimerec', '0003_auto_20210403_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specified', 'Not Specified')], max_length=20),
        ),
    ]
