# Generated by Django 3.1.7 on 2021-04-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0009_delete_user'),
        ('crimerec', '0007_auto_20210411_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crime_category',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crime_description',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crime_district',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crime_punishment',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crimedate',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='crimelocation',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='jail_name',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='sentence_status',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='victim_name',
        ),
        migrations.CreateModel(
            name='CriminalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_category', models.CharField(choices=[('Robbery', 'Robbery'), ('Cyber-crime', 'Cyber-crime'), ('Domestic violence', 'Domestic violence'), ('Sexual Assault', 'Sexual Assault'), ('Child Abuse', 'Child Abuse'), ('Terrorism', 'Terrorism'), ('Violent Crime', 'Violent Crime'), ('Corruption', 'Corruption'), ('Poaching', 'Poaching')], max_length=20)),
                ('crime_district', models.CharField(choices=[('Select district', 'Select district'), ('Ahmednagar', 'Ahmednagar'), ('Akola', 'Akola'), ('Amravati', 'Amravati'), ('Aurangabad', 'Aurangabad'), ('Beed', 'Beed'), ('Bhandara', 'Bhandara'), ('Buldhana', 'Buldhana'), ('Chandrapur', 'Chandrapur'), ('Dhule', 'Dhule'), ('Gadchiroli', 'Gadchiroli'), ('Gondia', 'Gondia'), ('Hingoli', 'Hingoli'), ('Jalgaon', 'Jalgaon'), ('Jalna', 'Jalna'), ('Kolhapur', 'Kolhapur'), ('Latur', 'Latur'), ('Mumbai City', 'Mumbai City'), ('Mumbai Suburban', 'Mumbai Suburban'), ('Nagpur', 'Nagpur'), ('Nanded', 'Nanded'), ('Nandurbar', 'Nandurbar'), ('Nashik', 'Nashik'), ('Osmanabad', 'Osmanabad'), ('Palghar', 'Palghar'), ('Parbhani', 'Parbhani'), ('Pune', 'Pune'), ('Raigad', 'Raigad'), ('Ratnagiri', 'Ratnagiri'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Sindhudurg', 'Sindhudurg'), ('Solapur', 'Solapur'), ('Thane', 'Thane'), ('Wardha', 'Wardha'), ('Washim', 'Washim'), ('Yavatmal', 'Yavatmal')], default='', max_length=30)),
                ('crimedate', models.DateField(blank=True, null=True)),
                ('crimelocation', models.CharField(blank=True, max_length=30)),
                ('victim_name', models.CharField(default='', max_length=500)),
                ('crime_description', models.TextField()),
                ('sentence_status', models.TextField(max_length=500)),
                ('crime_punishment', models.TextField()),
                ('case_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addcases.case')),
                ('criminal_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crimerec.criminalrecord')),
            ],
        ),
    ]
