# Generated by Django 3.1.7 on 2021-04-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimerec', '0009_auto_20210415_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalcase',
            name='criminal_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='crimcase', to='crimerec.criminalrecord'),
        ),
    ]
