# Generated by Django 3.1.7 on 2021-03-19 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('case_category', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('crime_location', models.CharField(max_length=100)),
                ('crime_date', models.CharField(max_length=10)),
                ('case_added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_io', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addcases.user')),
            ],
        ),
    ]
