# Generated by Django 3.1.7 on 2021-03-19 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0002_auto_20210320_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
