# Generated by Django 3.1.7 on 2021-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0003_case_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='passcode',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tracking_id',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
