# Generated by Django 3.1.7 on 2021-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0004_auto_20210320_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complainant_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='complainant_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='complainant_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
