# Generated by Django 3.1.7 on 2021-03-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0005_auto_20210320_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(db_column='case', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='case',
            table='case',
        ),
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accused_name', models.CharField(default='', max_length=100)),
                ('accused_contact', models.CharField(blank=True, max_length=10)),
                ('accused_email', models.EmailField(default='', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='addcases.case')),
            ],
            options={
                'db_table': 'accused',
                'unique_together': {('case', 'accused_name', 'accused_contact', 'accused_email')},
            },
        ),
    ]
