# Generated by Django 3.1.7 on 2021-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0006_auto_20210320_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accused_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='accused_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='accused_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='case_dsp_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='case',
            table=None,
        ),
        migrations.DeleteModel(
            name='Accused',
        ),
    ]
