# Generated by Django 3.1.7 on 2021-03-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210320_1910'),
        ('addcases', '0007_auto_20210320_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_io',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
