# Generated by Django 3.1.7 on 2021-03-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0008_auto_20210320_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
