# Generated by Django 3.1.7 on 2021-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0010_case_crime_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_category',
            field=models.CharField(choices=[('Robbery', 'Robbery'), ('Cyber-crime', 'Cyber-crime'), ('Domestic violence', 'Domestic violence'), ('Sexual Assault', 'Sexual Assault'), ('Child Abuse', 'Child Abuse'), ('Terrorism', 'Terrorism'), ('Violent Crime', 'Violent Crime'), ('Corruption', 'Corruption'), ('Poaching', 'Poaching')], default='', max_length=100),
        ),
    ]
