# Generated by Django 3.1.7 on 2021-03-22 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addcases', '0009_delete_user'),
        ('investigate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_id', models.CharField(max_length=3)),
                ('suspect_name', models.CharField(max_length=100)),
                ('suspect_contact', models.CharField(max_length=10)),
                ('suspect_address', models.TextField(max_length=300)),
                ('suspect_reason', models.TextField(max_length=5000)),
                ('edit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addcases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_id', models.CharField(max_length=3)),
                ('edit_title', models.CharField(max_length=100)),
                ('edit_content', models.TextField(max_length=5000)),
                ('edit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addcases.case')),
            ],
        ),
    ]
