# Generated by Django 3.1.7 on 2021-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('victim_name', models.CharField(max_length=255)),
                ('io_name', models.CharField(max_length=70)),
                ('io_id', models.CharField(max_length=15)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('category', models.CharField(max_length=70)),
                ('victim_id', models.CharField(max_length=15)),
                ('crime_loc', models.CharField(max_length=255)),
                ('crime_date', models.CharField(max_length=20)),
            ],
        ),
    ]
