# Generated by Django 3.1.7 on 2021-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='timeStamp',
        ),
        migrations.AlterField(
            model_name='case',
            name='crime_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
