# Generated by Django 3.1.7 on 2021-03-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addcases', '0009_delete_user'),
        ('project1', '0003_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status_no', models.CharField(max_length=3)),
                ('change_description', models.TextField(max_length=500)),
                ('case_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addcases.case')),
            ],
        ),
    ]
