# Generated by Django 3.1.7 on 2021-03-22 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_casestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestatus',
            old_name='change_description',
            new_name='status_content',
        ),
        migrations.AddField(
            model_name='casestatus',
            name='status_title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
